project:
  type: website
  output-dir: docs
website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cours_psycho.qmd
        text: Stats pour Psycho
      - href: cours_ONIRIS.qmd
        text: Cours ONIRIS
      - href: publications.qmd
        text: Publications
      - href: communications.qmd
        text: Communications

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

