project:
  type: website
  output-dir: docs

website:
  title: "JMG Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cours_psycho.qmd
        text: Cours de statistiques pour étudiants en psychologie
      - href: publications.qmd
        text: Publications
      - href: communications.qmd
        text: Communications

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

