---
title: "cours ONIRIS"
---

## Cours Ing1

### EC551 Statistique descriptive

1.  [Diaporama du Cours](cours_ONIRIS/EC551/cours.pdf)

2.  [TD1 avec correction](cours_ONIRIS/EC551/TD1_correct.pdf)

3.  [TD2 avec correction](cours_ONIRIS/EC551/TD2_correct.pdf)

***Projet à réaliser en binôme :***

-   [sujet](cours_ONIRIS/EC551/sujet23-24.pdf)

-   [data](cours_ONIRIS/EC551/data.csv)

### EC552 Intro à R

1.  [Prise en main de R (Séances 1 à 3) avec correction](cours_ONIRIS/EC552/1-3_premiers_pas.html)

2.  [Graphiques dans R (Séances 4 et 5) avec correction](cours_ONIRIS/EC552/4-5_graphiques.html)

3.  [Programmer dans R (Séances 6 et 7) avec correction](cours_ONIRIS/EC552/6-7_programmer_R.html)

### EC503 Algorithmique et programmation

1.  [Découverte de R (Séances 1 à 3) avec correction](cours_ONIRIS/EC503/TD1-3_correct.pdf)

2.  [Matrices et data frame (Séances 4 à 6)](cours_ONIRIS/EC503/TD4-6.pdf)

3.  [Graphiques dans R (Séances 7 à 10)](cours_ONIRIS/EC503/TD7-10.pdf)

4.  [Conditions, boucles, fonctions dans R (Séances 11 à 16)](cours_ONIRIS/EC503/TD11-16.pdf)

## Cours Ing2

### EC7851 Mathématiques pour l'ingénieur 2

## Cours Ing3

### ECFG932 Techniques avancées en évaluation sensorielle : TRI-LIBRE

1.  [diaporama du cours](cours_ONIRIS/ECFG932/diapo_tri_libre.pdf)

2.  [sujet de TD](cours_ONIRIS/ECFG932/TD.pdf)

3.  [données de TD](cours_ONIRIS/ECFG932/data_orange.zip)
