---
title: "CV"
---

# 2025

- Gilet, AL., Galharret, JM. Age-related differences in a DRM task: affect as a mediator. Motiv Emot (2025). [10.1007/s11031-025-10118-0](https://doi.org/10.1007/s11031-025-10118-0)

- H. Farnia, P. Sautejeau-Rizzoni, J.-M. Galharret, M. Le-Guiriec, D. Bencharif, Does the equilibration time prior to freezing affect post-thaw motion characteristics of stallion spermatozoa?, Journal of Equine Veterinary Science, Volume 145, 2025, 105280, ISSN 0737-0806,
[10.1016/j.jevs.2024.105280](https://doi.org/10.1016/j.jevs.2024.105280).


-   Galharret, J.M., Mahieu, B., Ratel, J., Krystalli, K., Pissaridi, K., Vigneau, E., Engel, E., Implementation of sample pooling to strengthen the self-monitoring in the food industry: Case study of mycotoxins in cereals, Food Research International, 2025, 115937, ISSN 0963-9969,[10.1016/j.foodres.2025.115937](https://doi.org/10.1016/j.foodres.2025.115937).

- Molinéro-Demilly, V., Charki, A., Lyonnet, B., Galharret, J.M., Joffrion, C., Effects of quality management on well-being at work and performance in a research laboratory: an exploratory study International. Journal of Quality & Reliability Management.

# 2024

-   Humeau, C., Guimard, P., Nocus, I., Casas F., Galharret JM. Well-being at School of 10-year-old Students Living in France in a Bilingual Family Language Context with a Minorated Language: Role of Teacher-Student and Peer Relationship Satisfaction. Child Ind Res (2024). [10.1007/s12187-024-10128-3](https://doi.org/10.1007/s12187-024-10128-3)

-   Toussaint E, Florin A, Galharret JM. Le point de vue des enfants en foyer et famille d'accueil sur leur santé : étude comparative. Sante Publique. 2024 Feb 23;35(6):17-25. French. . PMID: 38388398. [10.3917/spub.236.0017](https://doi.org/10.3917/spub.236.0017)

# 2023

-   Couteau, C., Philippe, A., Galharret, JM. et al. UV filters in everyday cosmetic products, a comparative study. Environ Sci Pollut Res (2023). [10.1007/s11356-023-31330-w](https://doi.org/10.1007/s11356-023-31330-w)

-   Fleury-Bahi G, Sapin A, Navarro O, Boudoukha AH, Galharret J-M, Bret A and Congard A (2023) Willingness to be vaccinated against COVID-19: the role of risk perception, trust in institutions, and affects. Front. Psychol. 14:1182114. [10.3389/fpsyg.2023.1182114](https://doi.org/10.3389/fpsyg.2023.1182114)

-   Humeau, C., Guimard, P., Nocus, I., & Galharret, J.-M. (2023). Parental language practices and children's use of the minority language: The mediating role of children's language attitudes. International Journal of Bilingualism. [10.1177/13670069231207326](https://doi.org/10.1177/13670069231207326).

-   G. Dagher, A. Martin, J.M. Galharret, L. Moulin, J.P. Croué, B. Teychene (2023). Forecasting multicycle hollow fiber ultrafiltration fouling using time series analysis, Journal of Water Process Engineering, Volume 56, 2023, 104441, ISSN 2214-7144, [10.1016/j.jwpe.2023.104441](https://doi.org/10.1016/j.jwpe.2023.104441).

-   Guinaudeau, C., Galharret, J., Roussiau, N. & Renard, E. (2023). Spiritualité explicite, préférence pour le naturel et croyances à l'efficacité de l'homéopathie. Bulletin de psychologie, , 1b-21b. [10.3917/bupsy.pr1.0002](https://doi.org/10.3917/bupsy.pr1.0002)

-   Ollivaud, J., Galharret, J.M., & Roussiau, N. (2023). Explicit spirituality, self-esteem and the mechanisms of social and temporal comparison. Spiritual Psychology and Counseling, 8(1), 83--102. [10.37898/spc.2023.8.1.187](https://doi.org/10.37898/spc.2023.8.1.187)

# 2022

-   Congard A., Galharret J.-M., Sapin A., Bret A., Fleury-Bahi G., Khocha A., Navarro O., Boudoukha A., How regulation strategies protected or worsened emotional experience during France's three lockdowns : Prepandemic versus pandemic comparisons and longitudinal approach, Acta Psychologica, Volume 234, 2023, 103857, ISSN 0001- 6918, [10.1016/j.actpsy.2023.103857](https://doi.org/10.1016/j.actpsy.2023.103857)

-   Ndobo A., Faure A., Galharret J.-M., Sarda E. & Debont L. (2022): The coping strategies of individuals in multiple jeopardy settings: the case of unemployed older women, The Journal of Social Psychology, [10.1080/00224545.2022.2143313](https://doi.org/10.1080/00224545.2022.2143313)

-   Toussaint Emmanuelle, Florin Agnès, Galharret Jean-Michel et al., « Inquiétude suscitée par la Covid-19 et soutien perçu par les enfants et les adolescents durant la pandémie en France », Enfance, 2022/4 (N° 4), p. 435-454. [10.3917/enf2.224.0435](https://doi.org/10.3917/enf2.224.0435).

-   Fleury-Bahi, G., Galharret, J.-M., Lemée, C., Wittenberg, I., Olivos, P., Loureiro, A., Jeuken, Y., Laïlle, P., & Navarro, O. (2022). Nature and well-being in seven European cities: The moderating effect of connectedness to nature. Applied Psychology: Health and Well-Being, 1-- 20. [10.1111/aphw.12390](https://doi.org/10.1111/aphw.12390)

-   Mercier N., Galharret J.-M., Tribolo C., Kreutzer S., and Philippe A. (2022) Luminescence age calculation through Bayesian convolution of equivalent dose and dose-rate distributions: the De_Dr model Geochronology, 4, 297--310, 2022 [10.5194/gchron-4-297-2022](https://doi.org/10.5194/gchron-4-297-2022)

-   Navarro O., Galharret J.-M. , Lemée C., Olivos P., Loureiro A., Wittenberg I., Fleury-Bahy G. (2022) The brief version of the "Connectedness to Nature Scale": Factorial structure and invariance study across seven European cities. Ecopsychology. [10.1089/eco.2021.0058](https://doi.org/10.1089/eco.2021.0058)

-   A. Congard, A. Boudoukha, J.-M. Galharret, A. Bret, A. Sapin, O. Navarro, G. Fleury-Bahi, Conséquences psychologiques du premier confinement en France : différences individuelles et vécu affectif, Psychologie Française, 2022, [10.1016/j.psfr.2022.02.001](https://doi.org/10.1016/j.psfr.2022.02.001)

-   Galharret J.-M., Philippe A., Bayesian analysis for mediation and moderation using g−priors., Econometrics and Statistics (2022), doi: [10.1016/j.ecosta.2021.12.009](https://doi.org/10.1016/j.ecosta.2021.12.009)

# 2021

-   Galharret, J-M, Philippe, A., & Mercier, N. (2021). Detection of outliers with a Bayesian hierarchical model: application to the single-grain luminescence dating method. Electronic Journal Of Applied Statistical Analysis, 14(2), 318 - 338. [DOI](http://siba-ese.unisalento.it/index.php/ejasa/article/view/22661)

-   Gilet A-L, Evrard C, Galharret J-M and Colombel F (2021) The Moderating Role of Education on the Relationship Between Perceived Stereotype Threat and False Memory in Aging. Front. Psychol. [10.3389/fpsyg.2020.606249](https://doi.org/10.3389/fpsyg.2020.606249).

-   Navarro, O., Restrepo-Ochoa, D., Rommel, D., Galharret, J-M., & Fleury-Bahi, G. (2021). Validation of a brief version of the Difficulties in Emotion Regulation Scale with a Spanish speaking population (DERS-S SF). Rev. CES Psico, 14(2), [10.21615/cesp.5360](https://doi.org/10.21615/cesp.5360).

# 2020

-   Tessoulin, M., Galharret, J.-M. , Gilet, A.-L., & Colombel, F. (2020). Misinformation in aging: A new light with equivalence testing. The Journals of Gerontology, Series B: Psychological Sciences and Social Sciences. [10.1093/geronb/gbz057](https://doi.org/10.1093/geronb/gbz057)

-   A. Caillé, N. Courtois, J.-M. Galharret, C. Jeoffrion (2020). Influence du leadership habilitant sur le bien-être au travail et l'engagement organisationnel : étude comparative entre une organisation « habilitante » et une organisation « classique »,Psychologie du Travail et des Organisations, 2020, [10.1016/j.pto.2020.05.001](https://doi.org/10.1016/j.pto.2020.05.001).

# 2019

-   Kindelberger, C., Mallet, P. , & Galharret, J-M. (2019). Diversity of romantic experiences in late adolescence and their contribution to identity formation. Social Development, on line first, [10.1111/sode.12415](https://doi.org/10.1111/sode.12415).

-   Kindelberger, C., Safont-Mottay, C., Lannegrand-Willems, L. & Galharret, J-M. (2019). Searching for autonomy before the transition for higher education: how do identity and self-determined academic motivation co-evolve? Journal of Youth and Adolescence, online first, [10.1007/s10964-019-01137-5](https://doi.org/10.1007/s10964-019-01137-5).

-   Bacro F., Coudronnière C., Gaudonville T., Galharret J-M., Ferrière S., Florin A. & Guimard P. (2019) The French adaptation of the Satisfaction with Life Scale (SWLS): Factorial structure, age, gender and time-related invariance in children and adolescents, European Journal of Developmental Psychology, [10.1080/17405629.2019.1680359](https://doi.org/10.1080/17405629.2019.1680359)
