---
title: "Publications"
---

# 2023 

* Guinaudeau, C., Galharret, J., Roussiau, N. & Renard, E. (2023). Spiritualité explicite, préférence pour le naturel et croyances à l’efficacité de l’homéopathie. Bulletin de psychologie, , 1b-21b. [10.3917/bupsy.pr1.0002](https://doi.org/10.3917/bupsy.pr1.0002)

* Ollivaud, J., Galharret, J.M., & Roussiau, N. (2023). Explicit spirituality, self-esteem and the mechanisms of social and temporal comparison. Spiritual Psychology and Counseling, 8(1), 83–102.
[10.37898/spc.2023.8.1.187](https://doi.org/10.37898/spc.2023.8.1.187) 


# 2022

* Congard A., Galharret J.-M., Sapin A., Bret A., Fleury-Bahi G., Khocha A., Navarro O., Boudoukha A., How regulation strategies protected or worsened emotional experience during France’s three lockdowns : Prepandemic versus pandemic comparisons and longitudinal approach, Acta Psychologica, Volume 234, 2023, 103857, ISSN 0001- 6918, [10.1016/j.actpsy.2023.103857](https://doi.org/10.1016/j.actpsy.2023.103857)

* Ndobo A., Faure A., Galharret J.-M., Sarda E. & Debont L. (2022): The coping strategies of individuals in multiple jeopardy settings: the case of unemployed older women, The Journal of Social Psychology,  [10.1080/00224545.2022.2143313](https://doi.org/10.1080/00224545.2022.2143313)

* Fleury-Bahi, G.,  Galharret, J.-M.,  Lemée, C.,  Wittenberg, I.,  Olivos, P.,  Loureiro, A.,  Jeuken, Y.,  Laïlle, P., & Navarro, O. (2022).  Nature and well-being in seven European cities: The moderating effect of connectedness to nature. Applied Psychology: Health and Well-Being,  1– 20. [10.1111/aphw.12390](https://doi.org/10.1111/aphw.12390)

* Mercier N., Galharret J.-M., Tribolo C., Kreutzer S., and Philippe A. (2022) Luminescence age calculation through Bayesian convolution of equivalent dose and dose-rate distributions: the De_Dr model Geochronology, 4, 297–310, 2022 [10.5194/gchron-4-297-2022](https://doi.org/10.5194/gchron-4-297-2022)

* Navarro O., Galharret J.-M. , Lemée C., Olivos P., Loureiro A., Wittenberg I., Fleury-Bahy G. (2022) The brief version of the “Connectedness to Nature Scale”: Factorial structure and invariance study across seven European cities. Ecopsychology. [10.1089/eco.2021.0058](https://doi.org/10.1089/eco.2021.0058)

* A. Congard, A. Boudoukha, J.-M. Galharret, A. Bret, A. Sapin, O. Navarro, G. Fleury-Bahi, Conséquences psychologiques du premier confinement en France : différences individuelles et vécu affectif, Psychologie Française, 2022, [10.1016/j.psfr.2022.02.001](https://doi.org/10.1016/j.psfr.2022.02.001)

* Galharret J.-M., Philippe A., Bayesian analysis for mediation and moderation using g−priors., Econometrics and Statistics (2022), doi: [10.1016/j.ecosta.2021.12.009](https://doi.org/10.1016/j.ecosta.2021.12.009)


# 2021

* Galharret, J-M, Philippe, A., & Mercier, N. (2021). Detection of outliers with a Bayesian hierarchical model: application to the single-grain luminescence dating method. Electronic Journal Of Applied Statistical Analysis, 14(2), 318 - 338. [DOI](http://siba-ese.unisalento.it/index.php/ejasa/article/view/22661)

* Gilet A-L, Evrard C, Galharret J-M and Colombel F (2021) The Moderating Role of Education on the Relationship Between Perceived Stereotype Threat and False Memory in Aging. Front. Psychol. [10.3389/fpsyg.2020.606249](https://doi.org/10.3389/fpsyg.2020.606249).

* Navarro, O., Restrepo-Ochoa, D., Rommel, D., Galharret, J-M., & Fleury-Bahi, G. (2021). Validation of a brief version of the Difficulties in Emotion Regulation Scale with a Spanish speaking population (DERS-S SF). Rev. CES Psico, 14(2), [10.21615/cesp.5360](https://doi.org/10.21615/cesp.5360).

# 2020

* Tessoulin, M., Galharret, J.-M. , Gilet, A.-L., & Colombel, F. (2020). Misinformation in aging: A new light with equivalence testing. The Journals of Gerontology, Series B: Psychological Sciences and Social Sciences.  [10.1093/geronb/gbz057](https://doi.org/10.1093/geronb/gbz057)

* A. Caillé, N. Courtois, J.-M. Galharret, C. Jeoffrion (2020). Influence du leadership habilitant sur le bien-être au travail et l’engagement organisationnel : étude comparative entre une organisation « habilitante » et une organisation « classique »,Psychologie du Travail et des Organisations, 2020, [10.1016/j.pto.2020.05.001](https://doi.org/10.1016/j.pto.2020.05.001).


# 2019 

* Kindelberger, C., Mallet, P. , & Galharret, J-M. (2019). Diversity of romantic experiences in late adolescence and their contribution to identity formation. Social Development, on line first, [10.1111/sode.12415](https://doi.org/10.1111/sode.12415).

* Kindelberger, C., Safont-Mottay, C., Lannegrand-Willems, L. & Galharret, J-M. (2019). Searching for autonomy before the transition for higher education: how do identity and self-determined academic motivation co-evolve? Journal of Youth and Adolescence, online first,  [10.1007/s10964-019-01137-5](https://doi.org/10.1007/s10964-019-01137-5).

* Bacro F., Coudronnière C., Gaudonville T., Galharret J-M., Ferrière S., Florin A. & Guimard P. (2019) The French adaptation of the Satisfaction with Life Scale (SWLS): Factorial structure, age, gender and time-related invariance in children and adolescents, European Journal of Developmental Psychology,  [10.1080/17405629.2019.1680359](https://doi.org/10.1080/17405629.2019.1680359)